title: "AQCE"
description: "Awesome Quantum Computing Experiments: A curated collection of notable quantum computing experiments"
theme: just-the-docs
baseurl: "/awesome-quantum-computing-experiments"
url: "https://francoismarieleregent.xyz"

# Theme settings
color_scheme: light
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/francois-marie/awesome-quantum-computing-experiments"

# Navigation
nav_order:
  home: 1
  experiments: 2

# External navigation links with icons
nav_external_links:
  - title: "View on GitHub"
    url: https://github.com/francois-marie/awesome-quantum-computing-experiments
    hide_icon: false # This will show the GitHub icon
    opens_in_new_tab: true

# Build settings
markdown: kramdown
sass:
  style: compressed
  sourcemap: never

plugins:
  - jekyll-include-cache
  - jekyll-feed

# Include generated plot files in the site
include:
  - out/js
  - out/png
  - out/plots
  - assets/js
  - assets/css

# Keep the generated files during Jekyll build
keep_files:
  - out
  - assets

# Exclude development files from build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
  - tests/
  - "*.py"
  - "*.pyc"
  - requirements*.txt
  - pyproject.toml
  - venv/
  - __pycache__/

# Just the Docs specific settings
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Aux links for the upper right navigation
aux_links_new_tab: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/francois-marie/awesome-quantum-computing-experiments" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
