paths:
  data:
    qec: data/qec_exp.csv
    msd: data/msd_exp.csv
    entangled: data/entangled_state_error_exp.csv
    qubit_count: data/qubit_count.csv
    physical_qubits: data/physical_qubits.csv
  output:
    plots: out/plots
    readme: README.md

plots:
  nkd: nkd_plot.png
  qec_time: qec_time_evolution.png
  entangled: entangled_state_error_vs_year.png
  qubit_count: qubit_count_vs_year.png
  coherence_times: coherence_times.png

plot_settings:
  figsize: [3.5, 2.5]  # Standard single-column width
  figsize_double: [7.2, 4]  # Double-column width
  fontsize:
    title: 9
    label: 8
    tick: 7
    annotation: 6
    legend: 6
  style:
    palette: 'Set2'  # Professional colorblind-friendly palette
    alpha: 0.9
    linewidth: 1
    figure:
      facecolor: 'white'
      dpi: 600  # Higher DPI for publication
    axes:
      facecolor: 'white'
      edgecolor: 'black'
      grid: true
      spines:
        top: false
        right: false
        bottom: true
        left: true
    grid:
      color: '#E6E6E6'
      linestyle: ':'
      alpha: 0.5
    text:
      color: 'black'
    ticks:
      color: 'black' 