name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'))
    
    steps:
    - name: Checkout main branch first
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    
    - name: Verify generated files exist
      run: |
        echo "=== Checking for generated files on main branch ==="
        ls -la out/ || echo "No out directory"
        ls -la out/js/ || echo "No JS files"
        ls -la out/png/ || echo "No PNG files"
    
    - name: Clean workspace
      run: |
        rm -rf _site
        rm -rf .jekyll-cache
        rm -rf vendor
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    
    - name: Clean Gemfile.lock
      run: rm -f Gemfile.lock
    
    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install
    
    - name: Build and deploy
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages
        keep_history: true
        jekyll_build_options: "--trace" 