name: Deploy GitHub Pages Redirect

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-redirect:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    
    - name: Create redirect site
      run: |
        mkdir -p _redirect_site
        cp redirect.html _redirect_site/index.html
        
        # Create a simple 404 page that also redirects
        cp redirect.html _redirect_site/404.html
        
        # Create CNAME file if you want to use a custom domain for the redirect
        # echo "your-custom-domain.com" > _redirect_site/CNAME
        
        echo "Created redirect site:"
        ls -la _redirect_site/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_redirect_site
        force_orphan: true 