name: Deploy Jekyll site

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        ref: gh-pages

    - name: Copy latest plots and data
      run: |
        git config --global --add safe.directory /github/workspace
        git checkout origin/main -- .
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Clean Gemfile.lock
      run: rm -f Gemfile.lock
    
    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install
    
    - name: Build and deploy
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages 